name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 * * * *'  # 每小时检查一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Caddy version
      id: get-version
      run: |
        RAW_VERSION=$(curl -sL https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r '.tag_name')
        # 去除版本号前的v字符
        CLEAN_VERSION="${RAW_VERSION#v}
        # 输出标准化版本号
        echo "version=$CLEAN_VERSION" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version }}
          ghcr.io/${{ github.repository }}:latest
        build-args: |
          CADDY_VERSION=${{ steps.get-version.outputs.version }}
